# Generated by Django 5.0.6 on 2024-05-14 08:40

import app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server', models.CharField(max_length=150, verbose_name='Server')),
                ('login', models.CharField(default='reader', max_length=50, null=True, verbose_name='Identifiant')),
                ('password', models.CharField(default='m1234', max_length=500, verbose_name='Mot de Passe')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=app.models.image_upload_path)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('value', models.CharField(max_length=150)),
                ('base', models.CharField(max_length=150)),
                ('table', models.CharField(default='', max_length=150, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connexion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.connexion')),
            ],
        ),
    ]
