# Generated by Django 5.0.6 on 2024-05-20 04:15

import app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe', models.CharField(blank=True, max_length=150, null=True)),
                ('compte_sage', models.CharField(blank=True, max_length=150, null=True)),
                ('compte_unif', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server', models.CharField(max_length=150, unique=True, verbose_name='Server')),
                ('login', models.CharField(default='reader', max_length=50, null=True, verbose_name='Identifiant')),
                ('password', models.CharField(default='m1234', max_length=500, verbose_name='Mot de Passe')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=app.models.image_upload_path)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('value', models.CharField(max_length=150)),
                ('base', models.CharField(max_length=150)),
                ('table', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, choices=[('X3', 'X3'), ('SAGE100', 'SAGE100')], max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connexion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.connexion')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_sage', models.CharField(blank=True, max_length=150, null=True)),
                ('compte_unif', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.TextField(blank=True)),
                ('target', models.IntegerField(unique=True)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('montant', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.societe')),
            ],
        ),
    ]
