# Generated by Django 5.0.6 on 2024-05-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='type',
            field=models.CharField(choices=[('X3', 'X3'), ('SAGE100', 'SAGE100')], default='X3', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
