# Generated by Django 5.0.6 on 2024-05-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_balance_id_balance_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.societe'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='target',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='societe',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
    ]
