# Generated by Django 5.0.6 on 2024-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_societe_type_alter_societe_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='table',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='type',
            field=models.CharField(blank=True, choices=[('X3', 'X3'), ('SAGE100', 'SAGE100')], max_length=150, null=True),
        ),
    ]
