# Generated by Django 5.0.6 on 2024-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_balance_societe_alter_balance_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
