# Generated by Django 5.0.6 on 2024-05-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_societe_table_alter_societe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='connexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.connexion'),
        ),
    ]
