# Generated by Django 5.0.6 on 2024-05-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_societe_connexion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connexion',
            name='server',
            field=models.CharField(max_length=150, unique=True, verbose_name='Server'),
        ),
    ]
