# Generated by Django 5.0.6 on 2024-05-17 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_connexion_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_sage', models.CharField(blank=True, max_length=150, null=True)),
                ('compte_unif', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.TextField(blank=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.IntegerField(unique=True)),
                ('balance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.balance')),
            ],
        ),
    ]
