# Generated by Django 5.0.6 on 2024-05-17 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_balance_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('societe', models.CharField(blank=True, max_length=150, null=True)),
                ('compte_sage', models.CharField(blank=True, max_length=150, null=True)),
                ('compte_unif', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
