# Generated by Django 5.0.6 on 2024-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='debit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='montant',
            field=models.FloatField(default=0),
        ),
    ]
